const LIMITE_ALUNOS_ABERTURA_TURMA = 5;       
const PRECO_MENSALIDADE = 500.0;
const DESCONTO_ATE_DIA_5 = 0.2;       

module.exports = {
  LIMITE_ALUNOS_ABERTURA_TURMA,
  PRECO_MENSALIDADE,
  DESCONTO_ATE_DIA_5,
};
